[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/catppuccin_latte.toml"
    # "~/.config/alacritty/themes/spacegray.toml"
]

[keyboard]
bindings = [
    { key = "k", mods = "Control", action = "ScrollLineUp"},
    { key = "k", mods = "Control|Shift", action = "ScrollHalfPageUp"},
    { key = "j", mods = "Control", action = "ScrollLineDown"},
    { key = "j", mods = "Control|Shift", action = "ScrollHalfPageDown"},
]

[env]
TERM="xterm-256color"
fish_vi_force_cursor="1"

[window]
decorations = "None"
opacity = 1.0

[scrolling]
history = 100000

[font]
size = 10.0

[font.normal]
family = "MesloLGSDZ Nerd Font"
style = "Regular"

[font.bold]
family = "MesloLGSDZ Nerd Font"
style = "Bold"

[font.italic]
family = "MesloLGSDZ Nerd Font"
style = "Italic"

[font.bold_italic]
family = "MesloLGSDZ Nerd Font"
style = "Bold Italic"
