[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/catppuccin_mocha.toml"
]

[keyboard]
bindings = [
    { key = "k", mods = "Control", action = "ScrollLineUp"},
    { key = "k", mods = "Control|Shift", action = "ScrollHalfPageUp"},
    { key = "j", mods = "Control", action = "ScrollLineDown"},
    { key = "j", mods = "Control|Shift", action = "ScrollHalfPageDown"},
]

[env]
TERM="xterm-256color"
fish_vi_force_cursor="1"

[window]
decorations = "None"
opacity = 1.0

[scrolling]
history = 100000

[font]
# normal = { family = "Commit Mono Nerd Font", style = "Regular"}
# bold = { family = "Commit Mono Nerd Font", style = "Bold"}
# italic = { family = "Commit Mono Nerd Font", style = "Italic"}
# bold_italic = { family = "Commit Mono Nerd Font", style = "Bold Italic"}
# offset = { x = 0, y = 1}
# size = 10.0

normal = { family = "TX-02", style = "Regular"}
bold = { family = "TX-02", style = "Bold"}
italic = { family = "TX-02", style = "Oblique"}
bold_italic = { family = "TX-02", style = "Bold Oblique"}
size = 10.0
offset = { x = 0, y = 0}

# normal = { family = "MesloLGSDZ Nerd Font", style = "Regular"}
# bold = { family = "MesloLGSDZ Nerd Font", style = "Bold"}
# italic = { family = "MesloLGSDZ Nerd Font", style = "Italic"}
# bold_italic = { family = "MesloLGSDZ Nerd Font", style = "Bold Italic"}
# size = 10.0
# offset = { x = 0, y = -3}

