colourful: true

filekinds:
  normal: {foreground: "#5c5f77"}
  directory: {foreground: "#1e66f5"}
  symlink: {foreground: "#04a5e5"}
  pipe: {foreground: "#8c8fa1"}
  block_device: {foreground: "#e64553"}
  char_device: {foreground: "#e64553"}
  socket: {foreground: "#acb0be"}
  special: {foreground: "#8839ef"}
  executable: {foreground: "#40a02b"}
  mount_point: {foreground: "#209fb5"}

perms:
  user_read: {foreground: "#4c4f69"}
  user_write: {foreground: "#df8e1d"}
  user_execute_file: {foreground: "#40a02b"}
  user_execute_other: {foreground: "#40a02b"}
  group_read: {foreground: "#5c5f77"}
  group_write: {foreground: "#df8e1d"}
  group_execute: {foreground: "#40a02b"}
  other_read: {foreground: "#6c6f85"}
  other_write: {foreground: "#df8e1d"}
  other_execute: {foreground: "#40a02b"}
  special_user_file: {foreground: "#8839ef"}
  special_other: {foreground: "#acb0be"}
  attribute: {foreground: "#6c6f85"}

size:
  major: {foreground: "#6c6f85"}
  minor: {foreground: "#04a5e5"}
  number_byte: {foreground: "#4c4f69"}
  number_kilo: {foreground: "#5c5f77"}
  number_mega: {foreground: "#1e66f5"}
  number_giga: {foreground: "#8839ef"}
  number_huge: {foreground: "#8839ef"}
  unit_byte: {foreground: "#6c6f85"}
  unit_kilo: {foreground: "#1e66f5"}
  unit_mega: {foreground: "#8839ef"}
  unit_giga: {foreground: "#8839ef"}
  unit_huge: {foreground: "#209fb5"}

users:
  user_you: {foreground: "#4c4f69"}
  user_root: {foreground: "#d20f39"}
  user_other: {foreground: "#8839ef"}
  group_yours: {foreground: "#5c5f77"}
  group_other: {foreground: "#8c8fa1"}
  group_root: {foreground: "#d20f39"}

links:
  normal: {foreground: "#04a5e5"}
  multi_link_file: {foreground: "#209fb5"}

git:
  new: {foreground: "#40a02b"}
  modified: {foreground: "#df8e1d"}
  deleted: {foreground: "#d20f39"}
  renamed: {foreground: "#179299"}
  typechange: {foreground: "#ea76cb"}
  ignored: {foreground: "#8c8fa1"}
  conflicted: {foreground: "#e64553"}

git_repo:
  branch_main: {foreground: "#4c4f69"}
  branch_other: {foreground: "#8839ef"}
  git_clean: {foreground: "#40a02b"}
  git_dirty: {foreground: "#d20f39"}

security_context:
  colon: {foreground: "#8c8fa1"}
  user: {foreground: "#5c5f77"}
  role: {foreground: "#8839ef"}
  typ: {foreground: "#acb0be"}
  range: {foreground: "#8839ef"}

file_type:
  image: {foreground: "#df8e1d"}
  video: {foreground: "#d20f39"}
  music: {foreground: "#40a02b"}
  lossless: {foreground: "#179299"}
  crypto: {foreground: "#acb0be"}
  document: {foreground: "#4c4f69"}
  compressed: {foreground: "#ea76cb"}
  temp: {foreground: "#e64553"}
  compiled: {foreground: "#209fb5"}
  build: {foreground: "#acb0be"}
  source: {foreground: "#8839ef"}
  # source: {foreground: "#1e66f5"}

punctuation: {foreground: "#8c8fa1"}
date: {foreground: "#df8e1d"}
inode: {foreground: "#6c6f85"}
blocks: {foreground: "#7c7f93"}
header: {foreground: "#4c4f69"}
octal: {foreground: "#179299"}
flags: {foreground: "#8839ef"}

symlink_path: {foreground: "#04a5e5"}
control_char: {foreground: "#209fb5"}
broken_symlink: {foreground: "#d20f39"}
broken_path_overlay: {foreground: "#acb0be"}

