colourful: true

filekinds:
  normal: {foreground: "#b8c0e0"}
  directory: {foreground: "#8aadf4"}
  symlink: {foreground: "#91d7e3"}
  pipe: {foreground: "#8087a2"}
  block_device: {foreground: "#ee99a0"}
  char_device: {foreground: "#ee99a0"}
  socket: {foreground: "#5b6078"}
  special: {foreground: "#c6a0f6"}
  executable: {foreground: "#a6da95"}
  mount_point: {foreground: "#7dc4e4"}

perms:
  user_read: {foreground: "#cad3f5"}
  user_write: {foreground: "#eed49f"}
  user_execute_file: {foreground: "#a6da95"}
  user_execute_other: {foreground: "#a6da95"}
  group_read: {foreground: "#b8c0e0"}
  group_write: {foreground: "#eed49f"}
  group_execute: {foreground: "#a6da95"}
  other_read: {foreground: "#a5adcb"}
  other_write: {foreground: "#eed49f"}
  other_execute: {foreground: "#a6da95"}
  special_user_file: {foreground: "#c6a0f6"}
  special_other: {foreground: "#5b6078"}
  attribute: {foreground: "#a5adcb"}

size:
  major: {foreground: "#a5adcb"}
  minor: {foreground: "#91d7e3"}
  number_byte: {foreground: "#cad3f5"}
  number_kilo: {foreground: "#b8c0e0"}
  number_mega: {foreground: "#8aadf4"}
  number_giga: {foreground: "#c6a0f6"}
  number_huge: {foreground: "#c6a0f6"}
  unit_byte: {foreground: "#a5adcb"}
  unit_kilo: {foreground: "#8aadf4"}
  unit_mega: {foreground: "#c6a0f6"}
  unit_giga: {foreground: "#c6a0f6"}
  unit_huge: {foreground: "#7dc4e4"}

users:
  user_you: {foreground: "#cad3f5"}
  user_root: {foreground: "#ed8796"}
  user_other: {foreground: "#c6a0f6"}
  group_yours: {foreground: "#b8c0e0"}
  group_other: {foreground: "#8087a2"}
  group_root: {foreground: "#ed8796"}

links:
  normal: {foreground: "#91d7e3"}
  multi_link_file: {foreground: "#7dc4e4"}

git:
  new: {foreground: "#a6da95"}
  modified: {foreground: "#eed49f"}
  deleted: {foreground: "#ed8796"}
  renamed: {foreground: "#8bd5ca"}
  typechange: {foreground: "#f5bde6"}
  ignored: {foreground: "#8087a2"}
  conflicted: {foreground: "#ee99a0"}

git_repo:
  branch_main: {foreground: "#cad3f5"}
  branch_other: {foreground: "#c6a0f6"}
  git_clean: {foreground: "#a6da95"}
  git_dirty: {foreground: "#ed8796"}

security_context:
  colon: {foreground: "#8087a2"}
  user: {foreground: "#b8c0e0"}
  role: {foreground: "#c6a0f6"}
  typ: {foreground: "#5b6078"}
  range: {foreground: "#c6a0f6"}

file_type:
  image: {foreground: "#eed49f"}
  video: {foreground: "#ed8796"}
  music: {foreground: "#a6da95"}
  lossless: {foreground: "#8bd5ca"}
  crypto: {foreground: "#5b6078"}
  document: {foreground: "#cad3f5"}
  compressed: {foreground: "#f5bde6"}
  temp: {foreground: "#ee99a0"}
  compiled: {foreground: "#7dc4e4"}
  build: {foreground: "#5b6078"}
  source: {foreground: "#c6a0f6"}
  # source: {foreground: "#8aadf4"}

punctuation: {foreground: "#8087a2"}
date: {foreground: "#eed49f"}
inode: {foreground: "#a5adcb"}
blocks: {foreground: "#939ab7"}
header: {foreground: "#cad3f5"}
octal: {foreground: "#8bd5ca"}
flags: {foreground: "#c6a0f6"}

symlink_path: {foreground: "#91d7e3"}
control_char: {foreground: "#7dc4e4"}
broken_symlink: {foreground: "#ed8796"}
broken_path_overlay: {foreground: "#5b6078"}
